### ISSUE TITLE
Retry.init() got an unexpected keyword argument 'method_whitelist'

### ISSUE THREAD

**Issue by JFarq** [solesensei/notion-game-list#14]
I get the below error when I put in the cookie value:

TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist'

I appreciate the work on this!

**Comment by solesensei** [comment]
https://github.com/GeneralMills/pytrends/issues/591

**Comment by solesensei** [comment]
https://github.com/jamalex/notion-py/issues/386
