### ISSUE TITLE
SteamApiError

### ISSUE THREAD

**Issue by anatolevuc** [solesensei/notion-game-list#2]
Hi! 

I got the following error when I was trying to make list

`SteamApiError: __init__() got an unexpected keyword argument 'recurring_sub'`

**Comment by solesensei** [comment]
Can't reproduce, looks like extra argument in steam api object
Added ignore for all unknown attributes 629fad7ae2e7045f79d8f800b88ae65b97d511b6

Release [v0.0.5](../releases/tag/v0.0.5)
