### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment

### ISSUE THREAD

**Issue by elliswalker** [solesensei/notion-game-list#3]
Running NGL 0.0.4
went through my library of 500+ games, got most of them. then this occurred while importing to Notion:
```
Got 507 games!
Creating Notion template page...
Created!
Importing steam library games to Notion...
Imported: 59/507
UnboundLocalError: local variable 'e' referenced before assignment

Enter any key to exit
```

**Comment by solesensei** [comment]
Ok, this is bug, fixed it here f745ffe580a0a35ddfbc2c446439cf28dc3143ec

This bug hides real issue, so you need to run the script again to figure it out and open another issue with it here :)

Check release [v0.0.5](../releases/tag/v0.0.5)
