### ISSUE TITLE
ServiceError: date format

### ISSUE THREAD

**Issue by solesensei** [solesensei/notion-game-list#5]
```
Got 507 games!
Creating Notion template page...
Created!
Importing steam library games to Notion...
ServiceError: time data '2015 年 3 月 10 日' does not match any of formats '%d %b, %Y', '%b %d, %Y', '%b %Y'

Enter any key to exit
```

[game_info_cache.txt](https://github.com/solesensei/notion-game-list/files/7212699/game_info_cache.txt)

always breaks at the same point after loading `Circuit Breaker` so I assume there's a game with a bad date format just after that

can't figure how to reopen...

_Originally posted by @elliswalker in https://github.com/solesensei/notion-game-list/issues/4#issuecomment-925136915_

**Comment by solesensei** [comment]
@elliswalker
i don't know why, but **Cities: Skylines** and some other games have broken release dates
I also has the game in my library, and it was imported without any problems.

So i changed script to not fail on broken dates, just logging

Check [v0.0.7](../releases/tag/v0.0.7)

**Comment by solesensei** [comment]
@elliswalker close this issue, if error doesn't persist

**Comment by elliswalker** [comment]
worked just fine. skipped 3-4 entries. all with weird date formats. thanks for the fix!
I dont have a PR so I don't think I have the option to close this.
