### ISSUE TITLE
Crashes while fetching game data

### ISSUE THREAD

**Issue by Yoddikko** [solesensei/notion-game-list#6]
Game Battlerite Public Test id:427460 not found in Steam store, fetching details from library
AttributeError: 'SteamApp' object has no attribute 'img_logo_url'

**Comment by Yoddikko** [comment]
I created a pull requeste where I fix this problem. When you accept it you can also close this issue.

**Comment by solesensei** [comment]
In an [API GetOwnedGames](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0001.29) there is `img_logo_url` field, but it seams it's missing for your game.

So the [code breakes here](https://github.com/solesensei/notion-game-list/blob/master/ngl/games/steam.py#L144).

**Comment by Yoddikko** [comment]
> In an [API GetOwnedGames](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0001.29) there is `img_logo_url` field, but it seams it's missing for your game.
> 
> 
> 
> So the [code breakes here](https://github.com/solesensei/notion-game-list/blob/master/ngl/games/steam.py#L144).
> 
> 
> 
> 

I tryed to put a place holder image in case he couldn't retrieve the image. Not knowing Python I wasn't succesful but maybe it could be a fix?

**Comment by solesensei** [comment]
[I fount it](https://github.com/smiley/steamapi/blob/eb1cf49ecabc2de892f6581168a84c07a19cb36f/steamapi/user.py#L177), so the field `img_logo_url` is not required as I thought

**Comment by solesensei** [comment]
> I tryed to put a place holder image in case he couldn't retrieve the image. Not knowing Python I wasn't succesful but maybe it could be a fix?

Sure, it can be fixed. I'll take a look at it later this week. You can create PR with your fix. I'll check it later too

**Comment by Yoddikko** [comment]
> > I tryed to put a place holder image in case he couldn't retrieve the image. Not knowing Python I wasn't succesful but maybe it could be a fix?
> 
> 
> 
> Sure, it can be fixed. I'll take a look at it later this week. You can create PR with your fix. I'll check it later too

My code didn't work at all sadly. Hoping that you can give look.

Thanks again.
