### ISSUE TITLE
Time stamps into hours only

### ISSUE THREAD

**Issue by Yoddikko** [solesensei/notion-game-list#9]

**Comment by solesensei** [comment]
Can you add description to issue you wrote in PR? To retrieve context later

**Comment by Yoddikko** [comment]
> Can you add description to issue you wrote in PR? To retrieve context later

Yes sorry.

It would be cool to have a hours only time played stamp. Because if on Notion I want to sort for most played or less played the games I played only some minutes get mixed with the game I played hours. It happens because maybe on a game I have 100 minutes and on another game I have 2 hours. It should be on top the one with 2 hours, but instead it goes under the one with 100 minutes. I was trying to apply a fix that if you want I can show you my code but I never coded in Python and I got some errors. My solution by the way was transforming minutes in hours, so that for example 30 minutes would be 0.5 hours, so that the sorting would be working correctly and the output wuold be only never or in hours.
